### ISSUE TITLE
RTCs need limmited command access

### ISSUE THREAD

**Issue by ya64** [ya64/Toybot#18]
Potentially allow RTC limited command access e.g. ?whois or ?tag.

**Comment by mm12** [comment]
Need to add a role check, see if any role ID of executor matches RTC or equivalent role.

**Comment by ya64** [comment]
RTCs now have access to the tag and list tag commands, and I will soon make them have access to the role info, server info, and who is commands.

**Comment by ya64** [comment]
This should be easy to fix but I'm too tired to right now (its 4 am). I'll have it done in 9ish hours.

**Comment by ya64** [comment]
Fixed by pull request #35
