### ISSUE TITLE
Emojis do not show up properly

### ISSUE THREAD

**Issue by ya64** [ya64/Toybot#19]
Emoji's in messages show up as :emoji: instead of the actual emoji

**Comment by mm12** [comment]
show example

**Comment by mm12** [comment]
Is it only the ones that say :**V**emotename:? because those are the vortex emotes

**Comment by ya64** [comment]
Yes. Is there a way to make the bot use custom emotes?

**Comment by mm12** [comment]
there must be, if the original vortex did it. Try looking in the bot account settings, the one on the discord developer page.

**Comment by mm12** [comment]
Try adding the emotes [here](https://discord.com/developers/applications/710260415694635089/rich-presence/assets), make sure to name them correctly or change the code to have the correct name.

**Comment by MrOinky** [comment]
they need to use the emote IDs if used from an external server

**Comment by MrOinky** [comment]
for reference, writing an emoji as ```\:emoji:``` will send it with the emoji id which is what you need to reference to send the emoji properly.

**Comment by mm12** [comment]
try some of these:
:vSuccess:719308423619149854:
:discord:719308423619149854:
:patreon:719308423619149854:
:vWarning:717654834915835964:

**Comment by ya64** [comment]
They don't work

**Comment by MrOinky** [comment]
that is not correctly formatted

**Comment by MrOinky** [comment]
example of a correct one here: `<:whitecookie:682713693489725443>`

**Comment by ya64** [comment]
Well anyway Deshi said we should just use the server emojis

**Comment by MrOinky** [comment]
closing this because we have a working solution and it just needs to be executed

**Comment by mm12** [comment]
should i reopen this since it is moved back to the "to do"

**Comment by ya64** [comment]
@MrOinky  fixed it
