### ISSUE TITLE
Music funtions

### ISSUE THREAD

**Issue by mm12** [ya64/Toybot#21]
Music functions including blacklists. we can copy some from [here](https://github.com/jagrosh/MusicBot)

**Comment by mm12** [comment]
If you use the linked one, and give it the same bot token, it will all act as 1 bot with 2 prefixes kinda

**Comment by ya64** [comment]
I'd say it would be better to merge the code

**Comment by mm12** [comment]
yeah I agree but this way also works

**Comment by mm12** [comment]
This way works very well. Unless BC has objections, this might be good. 
Having separate prefix is handy as well because you dont need to change command names
