### ISSUE TITLE
random idea: secret code

### ISSUE THREAD

**Issue by mm12** [ya64/Toybot#26]
if you enter a certain strain of characters, the konami code for instance, DM user a suprise?

**Comment by mm12** [comment]
add a backdoor lmao 

im basically high since my meds wore off

**Comment by HJBit** [comment]
backdoor party time for poggists in bts maybe [prefix]say?

**Comment by mm12** [comment]
or.... the secret code just leads to a puzzle that ends in a rickroll `\s`
