### ISSUE TITLE
IP logger filter, could be added to blacklist for websites

### ISSUE THREAD

**Issue by HJBit** [ya64/Toybot#27]
punishments of them are left up to deshi etc: ip loggers = mute shorteners = warn, but check pins of #chat-lol there's a more in depth file of iploggers updated in the text file that's wip (xxx sites could be added not sure yet)  
it's basically already done, except for list of xxx sites which is also up to deshi to add or remove, could use current features now to do it

**Comment by ya64** [comment]
So you are suggesting that we check all the links to see if they have the same IP as an NSFW site?

**Comment by mm12** [comment]
that sounds like more work than needs to be done. plus, ip filters always have problems with ones that are not block or false blocked in my experience

**Comment by mm12** [comment]
lets run a toycat realm experiment and have a whitelist instead 
\s

**Comment by MrOinky** [comment]
no, theres a list of domains to check that are all ip grabbers and url shortners

**Comment by MrOinky** [comment]
its not at all IP related

**Comment by mm12** [comment]
ah

**Comment by mm12** [comment]
wait

**Comment by HJBit** [comment]
I already have the list, this is to stop people from grabbing other ips, like i said the nsfw is optional because we don't really need it

**Comment by mm12** [comment]
is this saying we need a filter for IP loggers, thats already in the bot from the [beginning](https://raw.githubusercontent.com/jagrosh/Vortex/master/lists/referral_domains.txt)

**Comment by MrOinky** [comment]
and its very easy to do, just match the domain to the message and if its a recommended url delete it and if its the direct domain of an ip grabber straight up mute the person who posted it, and try to resolve url shortners and check that way too

**Comment by HJBit** [comment]
>is this saying we need a filter for IP loggers, thats already in the bot from the beginning

not really, just saying to update the list with the one i have in pins

**Comment by mm12** [comment]
ah

**Comment by mm12** [comment]
kinda dumb we are using github as a chat site instead of the discord

**Comment by MrOinky** [comment]
yes the list is missing a lot of urls

**Comment by HJBit** [comment]
yeah we should probably move to the discord server, because no it's all over the place

**Comment by HJBit** [comment]
updated filter
