### ISSUE TITLE
Owner ID is constant, should be read from the application.config file

### ISSUE THREAD

**Issue by ya64** [ya64/Toybot#29]

**Comment by mm12** [comment]
I am going to see if I can fix this

**Comment by mm12** [comment]
I am also going to move the "game" variable there, instead of just making it separate from the wiki page

**Comment by mm12** [comment]
should we put the prefix in constants? it can already be changed in the bot though, but you can't disable the default

**Comment by ya64** [comment]
The prefix is already in constants

**Comment by mm12** [comment]
sorry i meant in the config so the default can be changed

**Comment by ya64** [comment]
If you want

**Comment by mm12** [comment]
Most of the constants really should be changeable if we want this to be able to be used in other servers, etc. the emote issue #11

**Comment by ya64** [comment]
This isn't intended to be used in other servers. I only wanted the owner thing to change so the person thats running it in tests can easily set themselves as the owner.

**Comment by ya64** [comment]
Oops I pressed the closed button

**Comment by mm12** [comment]
i see
