### ISSUE TITLE
Tag command needed

### ISSUE THREAD

**Issue by ya64** [ya64/Toybot#4]
?tag command to output common messages such as realm link.

**Comment by mm12** [comment]
Another way to do this: Create a channel just for storage and the bot. Have something similar to a message formatted a specific way to store the tags, or just have the bot store tag name + message ID/link, and copy and return it. Advantages would mean the bot would not have to store the tag server-side.

**Comment by ya64** [comment]
Well, I think that it would be much faster to store the tags on an embedded database opposed to on a Discord channel. Also, I've already written a file to read and write tags to a database so I might as well use it.
