### ISSUE TITLE
Custom censor list needed

### ISSUE THREAD

**Issue by ya64** [ya64/Toybot#6]
Custom Censor list (that makes sense as opposed to being plagued by Scunthorpe syndrome).

**Comment by mm12** [comment]
should also be a separate list to the 2 existing ones, using similar code

**Comment by mm12** [comment]
why is this done? I don't see the custom list separate

**Comment by ya64** [comment]
What do you mean by the custom list seperate?

**Comment by mm12** [comment]
nevermind, didn't know "filter" was a thing

**Comment by mm12** [comment]
fück
fūck
etc should be added as well as 
f`invisible character`uck
